### PR TITLE
Fixing empty entry source string

### LINKED ISSUE #484: Error when passing empty string into .entry()
So I lost an hour on this :expressionless:. When you do:

```js
new Duo(process.cwd()).entry('', 'css').run(console.log.bind(console))
```

You get:

```
Error: cannot find entry: source.css
```

Seems like you are not doing any type checking on [`this.raw`](https://github.com/duojs/duo/blob/3e4f8fe883bfcb901db92586c9f448f89f58b560/lib/file.js#L127) or [`this.src`](https://github.com/duojs/duo/blob/3e4f8fe883bfcb901db92586c9f448f89f58b560/lib/file.js#L105) throughout the code. Please use `== null`.

### PR DESCRIPTION
**Pull request by dominicbarnes**
I've made the code checking `raw` and `src` a little more specific and clear. I believe I introduced this bug when I used ESLint to remove `== undefined` from these spots.

Basically, I've made the code a bit longer, but it should be a lot easier to maintain. (this fixes #484 and adds a test so it won't regress again)

/cc @darsain

### CODE REVIEW

**Comment by darsain** [comment]
This will break when `this.src` or `this.raw` are `null`, or `object` from some reason. More robust would be flipping the equals and type checking a string, which doesn't leave any holes that might cause errors:

```js
if (typeof this.raw !== 'string')
```

Or maybe they can be Buffer objects and you need just an undefined check? Dunno the internals, but if that's the case, rather do double equals null, which checks null and undefined ([see double equality table](https://dorey.github.io/JavaScript-Equality-Table/)). Dunno how eslit, but this is the only double equals usage where jshint doesn't complain, because it's that useful.

**Comment by dominicbarnes** [comment]
@darsain I've gone ahead and allowed `== null` by updating the ESLint config. This matches what we had before, which means it should still fix the underlying issue.

**Comment by darsain** [comment]
Any reason for not doing the most robust `typeof this.raw !== 'string'` type check?

File: lib/file.js [hunk 1]
```diff
@@ -102,11 +102,12 @@ File.prototype.dependencies = function () {
  */
 
 File.prototype.load = function *() {
-  if (this.src) return this;
+  if (typeof this.src !== 'undefined') return this;
```
Comment (stephenmathieson) [inline lib/file.js]: this is just my ocd, but why use `typeof` rather than just comparing with `undefined`?  the latter is terse and [slightly faster](https://gist.github.com/stephenmathieson/ad70f8d680dcece6f40f)

Comment (dominicbarnes) [inline lib/file.js]: I was addressing the concern that just checking `undefined` excludes the possibility of `null`

**Comment by dominicbarnes** [comment]
@darsain Hmm, I'm open to that possibility. What I have here works, so I'm going to press on with merging it, we can change it later if it turns out to be a problem.

File: lib/file.js (hunk 1 above)
Comment (stephenmathieson) [inline lib/file.js]: still not worth changing, but...

```
> typeof null
'object'
```

**Comment by dominicbarnes** [comment]
If you guys find a bug in this implementation, please submit a PR with a breaking test.
